article_liste:
  path:     /
  defaults: { _controller: "FrontSiteBundle:TzArticle:index" }

article_details:
  path:     /article/{id}
  defaults: { _controller: "FrontSiteBundle:TzArticle:showArticle" }