# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: "@UserBundle/Resources/config/services.yml" }

parameters:
    locale: 'fr'
    mailer_transport: '%env(resolve:MAILER_TRANSPORT)%'
    mailer_host: '%env(resolve:MAILER_HOST)%'
    mailer_user: '%env(resolve:MAILER_USER)%'
    mailer_password: '%env(resolve:MAILER_PASSWORD)%'
    to_email_address: '%env(resolve:TO_EMAIL_ADDRESS)%'
    to_email_name: '%env(resolve:TO_EMAIL_NAME)%'
    to_cc_ct_email_address: '%env(resolve:TO_CC_CT_EMAIL_ADDRESS)%'
    to_cc_rc_email_address: '%env(resolve:TO_CC_RC_EMAIL_ADDRESS)%'
    from_email_address: '%env(resolve:FROM_EMAIL_ADDRESS)%'
    from_firstname: '%env(resolve:FROM_FIRSTNAME)%'
    stripe_api_secret_key: '%env(resolve:STRIPE_API_SECRET_SECRET)%'
    stripe_api_publishable_key: '%env(resolve:STRIPE_API_PUBLISHABLE_KEY)%'
    max_size_value_upload: '%env(resolve:MAX_SIZE_VALUE_UPLOAD)%'
    paypal_client_id: '%env(resolve:PAYPAL_CLIENT_ID)%'
    paypal_client_secret: '%env(resolve:PAYPAL_CLIENT_SECRET)%'
    id_klikandpay: '%env(resolve:ID_KLIKANDPAY)%'
    reporting_template_directory: '%kernel.project_dir%/public/reporting/'

services:
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Migrations}'

    lv.manager.user.role:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevRole\ServiceMetierDevRole
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.cms:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevCms\ServiceMetierDevCms
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.contact:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevContact\ServiceMetierDevContact
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.contact.site:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevContactSite\ServiceMetierDevContactSite
        arguments: [ "@doctrine.orm.entity_manager","@service_container",'%kernel.root_dir%'  ]
        public: true

    lv.manager.contact.devis:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevContactDevis\ServiceMetierDevContactDevis
        arguments: [ "@doctrine.orm.entity_manager","@service_container",'%kernel.root_dir%' ]
        public: true

    lv.manager.service.type:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevServiceType\ServiceMetierDevServiceType
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.service:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevService\ServiceMetierDevService
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.service.option.type:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevServiceOptionType\ServiceMetierDevServiceOptionType
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.service.option:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevServiceOption\ServiceMetierDevServiceOption
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.client:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevClient\ServiceMetierDevClient
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.email.newsletter:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevEmailNewsletter\ServiceMetierEmailNewsletter
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.message.newsletter:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevMessageNewsletter\ServiceMetierMessageNewsletter
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.faq:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevFaq\ServiceMetierDevFaq
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.order:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevOrder\ServiceMetierDevOrder
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.service.client:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevServiceClient\ServiceMetierDevServiceClient
        arguments: [ "@doctrine.orm.entity_manager","@service_container", "@translator" ]
        public: true

    lv.manager.service.client.jointe:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevServiceClientJointe\ServiceMetierDevServiceClientJointe
        arguments: [ "@doctrine.orm.entity_manager","@service_container",'%kernel.root_dir%' ]
        public: true

    lv.manager.user.service.client:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevUserServiceClient\ServiceMetierDevUserServiceClient
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.facture:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevFacture\ServiceMetierDevFacture
        arguments: [ "@doctrine.orm.entity_manager","@service_container","@translator" ]
        public: true

    lv.twig.file.exists:
        class: App\Techzara\Service\MetierManagerBundle\Twig\Extension\FileExistsExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    lv.manager.slide:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevSlide\ServiceMetierDevSlide
        arguments: [ "@doctrine.orm.entity_manager","@service_container",'%kernel.root_dir%' ]
        public: true

    lv.manager.portfolio.type:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevPortfolioType\ServiceMetierDevPortfolioType
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.portfolio:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevPortfolio\ServiceMetierDevPortfolio
        arguments: [ "@doctrine.orm.entity_manager","@service_container",'%kernel.root_dir%' ]
        public: true

    lv.manager.temoignage:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevTemoignage\ServiceMetierDevTemoignage
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    lv.manager.sitemap:
        class: App\Techzara\Service\MetierManagerBundle\Metier\DevSitemap\ServiceMetierDevSitemap
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true
