article_index:
  path:     /
  defaults: { _controller: "AdminBundle:TzArticle:index" }
  methods:  GET

article_new:
  path:     /new
  defaults: { _controller: "AdminBundle:TzArticle:new" }
  methods:  [GET, POST]

article_edit:
  path:     /{id}/edit
  defaults: { _controller: "AdminBundle:TzArticle:edit" }
  methods:  [GET, POST]

article_update:
  path:     /{id}/update
  defaults: { _controller: "AdminBundle:TzArticle:update" }
  methods:  [POST, PUT]


article_delete:
  path:     /{id}/delete
  defaults: { _controller: "AdminBundle:TzArticle:delete" }
  methods:  [GET, DELETE]

article_delete_group:
  path:     /delete-group
  defaults: { _controller: "AdminBundle:TzArticle:deleteGroup" }
  methods:  POST

article_delete_image_ajax:
  path:     /delete-image
  defaults: { _controller: "AdminBundle:TzArticle:deleteImageAjax" }
  methods:  POST
