news_index:
  path:     /
  defaults: { _controller: "AdminBundle:DevNews:index" }
  methods:  GET

news_new:
  path:     /new
  defaults: { _controller: "AdminBundle:DevNews:new" }
  methods:  [GET, POST]

news_edit:
  path:     /{id}/edit
  defaults: { _controller: "AdminBundle:DevNews:edit" }
  methods:  [GET, POST]

news_update:
  path:     /{id}/update
  defaults: { _controller: "AdminBundle:DevNews:update" }
  methods:  [POST, PUT]

news_delete:
  path:     /{id}/delete
  defaults: { _controller: "AdminBundle:DevNews:delete" }
  methods:  [GET, DELETE]

news_delete_group:
  path:     /delete-group
  defaults: { _controller: "AdminBundle:DevNews:deleteGroup" }
  methods:  POST