service_type_index:
    path:     /
    defaults: { _controller: "AdminBundle:DevServiceType:index" }
    methods:  GET

service_type_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DevServiceType:new" }
    methods:  [GET, POST]

service_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DevServiceType:edit" }
    methods:  [GET, POST]

service_type_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DevServiceType:update" }
    methods:  [POST, PUT]

service_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DevServiceType:delete" }
    methods:  [GET, DELETE]

service_type_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DevServiceType:deleteGroup" }
    methods:  POST