service_option_index:
    path:     /
    defaults: { _controller: "AdminBundle:DevServiceOption:index" }
    methods:  GET

service_option_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DevServiceOption:new" }
    methods:  [GET, POST]

service_option_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DevServiceOption:edit" }
    methods:  [GET, POST]

service_option_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DevServiceOption:update" }
    methods:  [POST, PUT]

service_option_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DevServiceOption:delete" }
    methods:  [GET, DELETE]

service_option_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DevServiceOption:deleteGroup" }
    methods:  POST