user_service_client_index:
    path:     /
    defaults: { _controller: "AdminBundle:DevUserServiceClient:index" }
    methods:  GET

user_service_client_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DevUserServiceClient:new" }
    methods:  [GET, POST]

user_service_client_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DevUserServiceClient:edit" }
    methods:  [GET, POST]

user_service_client_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DevUserServiceClient:update" }
    methods:  [POST, PUT]

user_service_client_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DevUserServiceClient:delete" }
    methods:  [GET, DELETE]

user_service_client_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DevUserServiceClient:deleteGroup" }
    methods:  POST

user_service_client_update_status_project:
    path:     /{id}/update-status-project-{_status}
    defaults: { _controller: "AdminBundle:DevUserServiceClient:updateStatusProject" }
    methods:  GET

user_service_client_detail:
    path:     /detail/{id}
    defaults: { _controller: "AdminBundle:DevUserServiceClient:detail" }
    methods:  GET